name: Run tests on push

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Scala environment
        uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.17.0

      - name: Coursier cache
        uses: coursier/cache-action@v6

      - name: Invoke sbt tests
        id: test
        run: |
          sbt "Test/test;Regression/test"
